// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "txn.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* TxnProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TxnProto_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TxnProto_IsolationLevel_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* TxnProto_Status_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_txn_2eproto() {
  protobuf_AddDesc_txn_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "txn.proto");
  GOOGLE_CHECK(file != NULL);
  TxnProto_descriptor_ = file->message_type(0);
  static const int TxnProto_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, txn_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, txn_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, isolation_level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, multipartition_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, read_set_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, write_set_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, arg_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, status_),
  };
  TxnProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TxnProto_descriptor_,
      TxnProto::default_instance_,
      TxnProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TxnProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TxnProto));
  TxnProto_IsolationLevel_descriptor_ = TxnProto_descriptor_->enum_type(0);
  TxnProto_Status_descriptor_ = TxnProto_descriptor_->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_txn_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TxnProto_descriptor_, &TxnProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_txn_2eproto() {
  delete TxnProto::default_instance_;
  delete TxnProto_reflection_;
}

void protobuf_AddDesc_txn_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\ttxn.proto\"\222\003\n\010TxnProto\022\016\n\006txn_id\030\001 \002(\003"
    "\022\020\n\010txn_type\030\n \001(\005\0221\n\017isolation_level\030\013 "
    "\001(\0162\030.TxnProto.IsolationLevel\022\026\n\016multipa"
    "rtition\030\014 \001(\010\022\020\n\010read_set\030\024 \003(\004\022\021\n\twrite"
    "_set\030\025 \003(\004\022\013\n\003arg\030\026 \001(\014\022 \n\006status\030\036 \001(\0162"
    "\020.TxnProto.Status\"Z\n\016IsolationLevel\022\020\n\014S"
    "ERIALIZABLE\020\000\022\014\n\010SNAPSHOT\020\001\022\022\n\016READ_COMM"
    "ITTED\020\002\022\024\n\020READ_UNCOMMITTED\020\003\"i\n\006Status\022"
    "\007\n\003NEW\020\000\022\n\n\006ACTIVE\020\001\022\t\n\005READY\020\002\022\013\n\007NETWO"
    "RK\020\003\022\013\n\007BLOCKED\020\004\022\013\n\007ABORTED\020\005\022\r\n\tCOMMIT"
    "TED\020\006\022\t\n\005TWOPC\020\007", 416);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "txn.proto", &protobuf_RegisterTypes);
  TxnProto::default_instance_ = new TxnProto();
  TxnProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_txn_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_txn_2eproto {
  StaticDescriptorInitializer_txn_2eproto() {
    protobuf_AddDesc_txn_2eproto();
  }
} static_descriptor_initializer_txn_2eproto_;


// ===================================================================

const ::google::protobuf::EnumDescriptor* TxnProto_IsolationLevel_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TxnProto_IsolationLevel_descriptor_;
}
bool TxnProto_IsolationLevel_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const TxnProto_IsolationLevel TxnProto::SERIALIZABLE;
const TxnProto_IsolationLevel TxnProto::SNAPSHOT;
const TxnProto_IsolationLevel TxnProto::READ_COMMITTED;
const TxnProto_IsolationLevel TxnProto::READ_UNCOMMITTED;
const TxnProto_IsolationLevel TxnProto::IsolationLevel_MIN;
const TxnProto_IsolationLevel TxnProto::IsolationLevel_MAX;
const int TxnProto::IsolationLevel_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* TxnProto_Status_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TxnProto_Status_descriptor_;
}
bool TxnProto_Status_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const TxnProto_Status TxnProto::NEW;
const TxnProto_Status TxnProto::ACTIVE;
const TxnProto_Status TxnProto::READY;
const TxnProto_Status TxnProto::NETWORK;
const TxnProto_Status TxnProto::BLOCKED;
const TxnProto_Status TxnProto::ABORTED;
const TxnProto_Status TxnProto::COMMITTED;
const TxnProto_Status TxnProto::TWOPC;
const TxnProto_Status TxnProto::Status_MIN;
const TxnProto_Status TxnProto::Status_MAX;
const int TxnProto::Status_ARRAYSIZE;
#endif  // _MSC_VER
const ::std::string TxnProto::_default_arg_;
#ifndef _MSC_VER
const int TxnProto::kTxnIdFieldNumber;
const int TxnProto::kTxnTypeFieldNumber;
const int TxnProto::kIsolationLevelFieldNumber;
const int TxnProto::kMultipartitionFieldNumber;
const int TxnProto::kReadSetFieldNumber;
const int TxnProto::kWriteSetFieldNumber;
const int TxnProto::kArgFieldNumber;
const int TxnProto::kStatusFieldNumber;
#endif  // !_MSC_VER

TxnProto::TxnProto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TxnProto::InitAsDefaultInstance() {
}

TxnProto::TxnProto(const TxnProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TxnProto::SharedCtor() {
  _cached_size_ = 0;
  txn_id_ = GOOGLE_LONGLONG(0);
  txn_type_ = 0;
  isolation_level_ = 0;
  multipartition_ = false;
  arg_ = const_cast< ::std::string*>(&_default_arg_);
  status_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TxnProto::~TxnProto() {
  SharedDtor();
}

void TxnProto::SharedDtor() {
  if (arg_ != &_default_arg_) {
    delete arg_;
  }
  if (this != default_instance_) {
  }
}

void TxnProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TxnProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TxnProto_descriptor_;
}

const TxnProto& TxnProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_txn_2eproto();  return *default_instance_;
}

TxnProto* TxnProto::default_instance_ = NULL;

TxnProto* TxnProto::New() const {
  return new TxnProto;
}

void TxnProto::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    txn_id_ = GOOGLE_LONGLONG(0);
    txn_type_ = 0;
    isolation_level_ = 0;
    multipartition_ = false;
    if (_has_bit(6)) {
      if (arg_ != &_default_arg_) {
        arg_->clear();
      }
    }
    status_ = 0;
  }
  read_set_.Clear();
  write_set_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TxnProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 txn_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &txn_id_)));
          _set_bit(0);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_txn_type;
        break;
      }
      
      // optional int32 txn_type = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_txn_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &txn_type_)));
          _set_bit(1);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(88)) goto parse_isolation_level;
        break;
      }
      
      // optional .TxnProto.IsolationLevel isolation_level = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isolation_level:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::TxnProto_IsolationLevel_IsValid(value)) {
            set_isolation_level(static_cast< ::TxnProto_IsolationLevel >(value));
          } else {
            mutable_unknown_fields()->AddVarint(11, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(96)) goto parse_multipartition;
        break;
      }
      
      // optional bool multipartition = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_multipartition:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &multipartition_)));
          _set_bit(3);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(160)) goto parse_read_set;
        break;
      }
      
      // repeated uint64 read_set = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_read_set:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 2, 160, input, this->mutable_read_set())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_read_set())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(160)) goto parse_read_set;
        if (input->ExpectTag(168)) goto parse_write_set;
        break;
      }
      
      // repeated uint64 write_set = 21;
      case 21: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_write_set:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 2, 168, input, this->mutable_write_set())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_write_set())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(168)) goto parse_write_set;
        if (input->ExpectTag(178)) goto parse_arg;
        break;
      }
      
      // optional bytes arg = 22;
      case 22: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_arg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_arg()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(240)) goto parse_status;
        break;
      }
      
      // optional .TxnProto.Status status = 30;
      case 30: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_status:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::TxnProto_Status_IsValid(value)) {
            set_status(static_cast< ::TxnProto_Status >(value));
          } else {
            mutable_unknown_fields()->AddVarint(30, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TxnProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 txn_id = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->txn_id(), output);
  }
  
  // optional int32 txn_type = 10;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->txn_type(), output);
  }
  
  // optional .TxnProto.IsolationLevel isolation_level = 11;
  if (_has_bit(2)) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      11, this->isolation_level(), output);
  }
  
  // optional bool multipartition = 12;
  if (_has_bit(3)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->multipartition(), output);
  }
  
  // repeated uint64 read_set = 20;
  for (int i = 0; i < this->read_set_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      20, this->read_set(i), output);
  }
  
  // repeated uint64 write_set = 21;
  for (int i = 0; i < this->write_set_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      21, this->write_set(i), output);
  }
  
  // optional bytes arg = 22;
  if (_has_bit(6)) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      22, this->arg(), output);
  }
  
  // optional .TxnProto.Status status = 30;
  if (_has_bit(7)) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      30, this->status(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TxnProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 txn_id = 1;
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->txn_id(), target);
  }
  
  // optional int32 txn_type = 10;
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(10, this->txn_type(), target);
  }
  
  // optional .TxnProto.IsolationLevel isolation_level = 11;
  if (_has_bit(2)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      11, this->isolation_level(), target);
  }
  
  // optional bool multipartition = 12;
  if (_has_bit(3)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->multipartition(), target);
  }
  
  // repeated uint64 read_set = 20;
  for (int i = 0; i < this->read_set_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(20, this->read_set(i), target);
  }
  
  // repeated uint64 write_set = 21;
  for (int i = 0; i < this->write_set_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(21, this->write_set(i), target);
  }
  
  // optional bytes arg = 22;
  if (_has_bit(6)) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        22, this->arg(), target);
  }
  
  // optional .TxnProto.Status status = 30;
  if (_has_bit(7)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      30, this->status(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TxnProto::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 txn_id = 1;
    if (has_txn_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->txn_id());
    }
    
    // optional int32 txn_type = 10;
    if (has_txn_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->txn_type());
    }
    
    // optional .TxnProto.IsolationLevel isolation_level = 11;
    if (has_isolation_level()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->isolation_level());
    }
    
    // optional bool multipartition = 12;
    if (has_multipartition()) {
      total_size += 1 + 1;
    }
    
    // optional bytes arg = 22;
    if (has_arg()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->arg());
    }
    
    // optional .TxnProto.Status status = 30;
    if (has_status()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
    }
    
  }
  // repeated uint64 read_set = 20;
  {
    int data_size = 0;
    for (int i = 0; i < this->read_set_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->read_set(i));
    }
    total_size += 2 * this->read_set_size() + data_size;
  }
  
  // repeated uint64 write_set = 21;
  {
    int data_size = 0;
    for (int i = 0; i < this->write_set_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->write_set(i));
    }
    total_size += 2 * this->write_set_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TxnProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TxnProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TxnProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TxnProto::MergeFrom(const TxnProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  read_set_.MergeFrom(from.read_set_);
  write_set_.MergeFrom(from.write_set_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_txn_id(from.txn_id());
    }
    if (from._has_bit(1)) {
      set_txn_type(from.txn_type());
    }
    if (from._has_bit(2)) {
      set_isolation_level(from.isolation_level());
    }
    if (from._has_bit(3)) {
      set_multipartition(from.multipartition());
    }
    if (from._has_bit(6)) {
      set_arg(from.arg());
    }
    if (from._has_bit(7)) {
      set_status(from.status());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TxnProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TxnProto::CopyFrom(const TxnProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TxnProto::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void TxnProto::Swap(TxnProto* other) {
  if (other != this) {
    std::swap(txn_id_, other->txn_id_);
    std::swap(txn_type_, other->txn_type_);
    std::swap(isolation_level_, other->isolation_level_);
    std::swap(multipartition_, other->multipartition_);
    read_set_.Swap(&other->read_set_);
    write_set_.Swap(&other->write_set_);
    std::swap(arg_, other->arg_);
    std::swap(status_, other->status_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TxnProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TxnProto_descriptor_;
  metadata.reflection = TxnProto_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
